version: 2
jobs:
  build:
    branches:
      only:
        - assignment5
    docker:
      - image: circleci/python:3.5-jessie
    working_directory: ~/webapp/WebProject
    steps:
      - checkout:
      - run:
          name: List directory
          command: cd webapp/WebProject && ls
      - run:
          name: Update packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Install packages for project
          command: sudo apt-get install python3 virtualenv python3-pip mysql-server python3-dev libmysqlclient-dev -y
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Create Virtualenv
          command: cd webapp/WebProject && virtualenv -p python3 djangoEnv
      - run:
          name: Enter Virtual env
          command: cd webapp/WebProject && source djangoEnv/bin/activate
      - run:
          name: Install Requirements
          command:  cd webapp/WebProject && source djangoEnv/bin/activate && pip3 install -r requirements.txt
      - run:
          name: Make Migrations
          command: cd webapp/WebProject && source djangoEnv/bin/activate && python3 manage.py makemigrations --settings=WebProject.settings_test
      - run:
          name: Migrate
          command: cd webapp/WebProject && source djangoEnv/bin/activate && python3 manage.py migrate --settings=WebProject.settings_test
      - run:
          name: Running Tests for webapp 
          command: cd webapp/WebProject && source djangoEnv/bin/activate  &&  python3 manage.py test --settings=WebProject.settings_test
      - run:
          name: Zip Project 
          command: cd webapp && zip -r ~/webapp.zip *
      - run:
          name: List directory
          command: cd ~/ && ls
      - run:
          name: Deploy to S3
          command: aws s3 cp ~/webapp.zip s3://code-deploy.csye6225-spring2019-sonij.me/
#       - run:
#           name: Deploy to AWS EC2
# <<<<<<< HEAD
#           command: aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name csye6225-webapp-deployment --description "My demo deployment" --s3-location bucket=code-deploy.csye6225-spring2019-sonij.me,bundleType=zip,key=webapp.zip
# =======
#           command: aws configure set region us-east-1 && aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name csye6225-webapp-deployment --description "My demo deployment" --s3-location bucket=code-deploy.csye6225-s19-mandakathils.me,bundleType=zip,key=webapp.zip
# >>>>>>> 198e51770a288a75cdfe3769eabece326b253f3d
