version: 2
jobs:
  build:
    branches:
      only:
        - assignment5
    docker:
      - image: circleci/python:3.5-jessie
    working_directory: ~/webapp/WebProject
    steps:
      - checkout:
      - run:
          name: List directory
          command: cd webapp/WebProject
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Install packages for project
          command: sudo apt-get install python3 virtualenv python3-pip mysql-server python3-dev libmysqlclient-dev -y
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Create Virtualenv
          command: virtualenv -p python3 djangoEnv
      - run:
          name: Enter Virtual env
          command: source djangoEnv/bin/activate
      - run:
          name: Install Requirements
          command: pip3 install -r requirements.txt
      - run:
          name: Make Migrations
          command: python3 manage.py makemigrations --settings=WebProject.settings_test
      - run:
          name: Migrate
          command: python3 manage.py migrate --settings=WebProject.settings_test
      - run:
          name: Migrate
          command: python3 manage.py test