
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloud Formation to build Continuos Integration and deployment stack for Circle CI

Parameters:
  AWSAccountId:
    Description: AWSAccountId
    Type: String
  CodeDeployApplicationName:
    Description: CodeDeployApplicationName
    Type: String
  AWSRegion:
    Description: AWS Region
    Type: String
  S3BucketName:
    Description: S3BucketName
    Type: String
Resources:

  CircleCIUser:
    Type: AWS::IAM::User
    Properties:
      UserName: CircleCI1
      Path: "/"
      LoginProfile:
        Password: Test@123
      Policies:
      - PolicyName: CodeDeployEC2S3
        PolicyDocument:
          Version: "2012-10-17"
          Statement: 
            Action: 
              - "s3:Get*"
              - "s3:List*"
            Effect: Allow
            Resource: !Join ["",["arn:aws:s3:::",!Ref S3BucketName,"/*"]]
      - PolicyName: CircleCIUploadToS3
        PolicyDocument:
          Version: "2012-10-17"
          Statement: 
            Action: 
              - "s3:PutObject"
            Effect: Allow
            Resource: !Join ["",["arn:aws:s3:::",!Ref S3BucketName,"/*"]]
      - PolicyName: CirlceCICodeDeploy
        PolicyDocument:
          Version: "2012-10-17"
          Statement: 
            - Effect: Allow
              Action: 
                - "codedeploy:RegisterApplicationRevision"
                - "codedeploy:GetApplicationRevision"
              Resource: 
                - !Join ["",["arn:aws:codedeploy:",!Ref AWSRegion,":",!Ref AWSAccountId,":application:",!Ref CodeDeployApplicationName]]
            - Effect: Allow
              Action: 
                - "codedeploy:CreateDeployment"
                - "codedeploy:GetDeployment"
              Resource: "*"
            - Effect: Allow
              Action: 
                - "codedeploy:GetDeploymentConfig"
              Resource: 
                - !Join ["",["arn:aws:codedeploy:",!Ref AWSRegion,":",!Ref AWSAccountId,":deploymentconfig:CodeDeployDefault.OneAtATime"]]
                - !Join ["",["arn:aws:codedeploy:",!Ref AWSRegion,":",!Ref AWSAccountId,":deploymentconfig:CodeDeployDefault.HalfAtATime"]]
                - !Join ["",["arn:aws:codedeploy:",!Ref AWSRegion,":",!Ref AWSAccountId,":deploymentconfig:CodeDeployDefault.AllAtOnce"]]
