version: 0.0

os: linux
files:
  - source: /
    destination: /home/centos/webapp
hooks:
  BeforeInstall:
    - location: cd_scripts/clean_server.sh
      timeout: 300
      runas: centos
  AfterInstall:
    - location: cd_scripts/install_os_dependencies.sh
      timeout: 300
      runas: centos
    - location: cd_scripts/install_python_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: cd_scripts/start_server.sh
      timeout: 300
      runas: centos
  # ApplicationStop:
  #   - location: scripts/stop_server.sh
  #     timeout: 300
  #     runas: rootpw